### ISSUE TITLE
Stops working after a while

### ISSUE THREAD

**Issue by martin67** [hnesland/telldusmq#2]
I've been running telldusmq for a while now (great program btw), but it always stops working after some time, usually about 20-30 hours. There are no error messages in the log and the program is still running, but no more MQTT messages are sent.

Running Rasbian on a Raspberry Pi (Pi2 ver B).

Any ideas? Is there some way for running in debug mode?

**Comment by hnesland** [comment]
Does it still receive messages from the Tellstick (should appear in the timestamped log)? What MQTT-broker/server are you using? My first assumption is re-connection issue if the connection to the broker is lost.

I will try to reproduce the error, thanks for reporting it.

**Comment by martin67** [comment]
Hi,

there are no more messages in the timestamped log (as listed in syslog); it
just stops. I'm using mosquitto on an Ubuntu host. I have some other MQTT
services running which are not affected, it's just the telldusmq parts.

Here's an example from yesterday:

Aug 21 22:02:33 hugin telldusmq[6367]: 2017/08/21 22:02:33 Publish to
'tellstick
/sensors/mandolyn/temperaturehumidity/73/temp' with '25.0'
Aug 21 22:02:33 hugin telldusmq[6367]: 2017/08/21 22:02:33 Publish to
'tellstick
/sensors/mandolyn/temperaturehumidity/73/humidity' with '53'
Aug 21 22:03:33 hugin telldusmq[6367]: 2017/08/21 22:03:33 Publish to
'tellstick
/sensors/mandolyn/temperaturehumidity/73/temp' with '25.0'
Aug 21 22:17:01 hugin CRON[20026]: (root) CMD (   cd / && run-parts
--report /et
c/cron.hourly)
Aug 21 22:47:23 hugin systemd[1]: Stopping Telldus - MQTT gateway...
Aug 21 22:47:23 hugin systemd[1]: Starting Telldus - MQTT gateway...
Aug 21 22:47:23 hugin systemd[1]: Started Telldus - MQTT gateway.
Aug 21 22:47:23 hugin telldusmq[20228]: 2017/08/21 22:47:23 Started Message
Queue for Telldus Core
Aug 21 22:47:23 hugin telldusmq[20228]: 2017/08/21 22:47:23 Subscribing to:
tellstick/events
Aug 21 22:47:23 hugin telldusmq[20228]: 2017/08/21 22:47:23 Subscribing to:
tellstick/device/#
Aug 21 22:47:33 hugin telldusmq[20228]: 2017/08/21 22:47:33 Publish to
'tellstick/sensors/mandolyn/temperaturehumidity/73/temp' with '25.0'

It just stopped somewhere after 22:17. I then manually restarted it at
22:47. I have a number of temperature sensors that send messages quite
often (as well as a number of switches that receive messages).




2017-08-22 15:28 GMT+02:00 Harald Nesland <notifications@github.com>:

**Comment by hnesland** [comment]
After some investigation, I may have stumble upon a bug. If the telldus daemon `telldusd` is restarted, the telldusmq-broker loses the binding. 

I'll look into if it is possible to detect a state where the callback from telldusd is lost, and then re-register it.

I can't confirm if this is what happens in your case, but it does sound like something related at least.

**Comment by hnesland** [comment]
Hi, I've rewritten some of the core tellstick-code and removed all the libtelldus-requirements. The libtelldus-client doesn't seem to support reconnecting to the server/unix sockets if it goes away, and there is no way of detecting that we lost the callback.

Instead of using the library, I've added some code for reading and writing to the unix sockets directly. This should also take care of any socket errors and recover. 

I'm running the latest version currently and it "seems to work fine", please try the updated code and report back :-)

**Comment by martin67** [comment]
Hi,

I've been running it now for 4 days without any problem, so I guess you
fixed the issue. Thanks!

2017-08-27 19:33 GMT+02:00 Harald Nesland <notifications@github.com>:

**Comment by hnesland** [comment]
Good to hear!
