### ISSUE TITLE
telldusmq and thingsboard

### ISSUE THREAD

**Issue by kjetilrong** [hnesland/telldusmq#3]
This is not a bug, but a question.
I'm trying to use telldusmq to send data to a thingsboard iot gatway.
Is it supposed that telldusmq should work as a server, on the port selected in the configuration file, or do telldusmq conect to a broker/server and send data to this?

192.168.10.99 is localhost for telldusmq.

when i try "go run main.go" i got this error:
017/11/05 11:52:23 Started Message Queue for Telldus Core
2017/11/05 11:52:23 Unable to connect to MQTT: Network Error : dial tcp 192.168.10.99:1882: getsockopt: connection refused
panic: Unable to connect to MQTT: Network Error : dial tcp 192.168.10.99:1882: getsockopt: connection refused

goroutine 1 [running]:
panic(0x8448e0, 0xc82015c140)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
log.Panicf(0xa31ae0, 0x1d, 0xc8200d5e78, 0x1, 0x1)
	/usr/lib/go-1.6/src/log/log.go:327 +0xd8
main.setupMqtt()

**Comment by hnesland** [comment]
Hi

Telldusmq needs a MQTT server software (like Mosquitto or RabbitMQ with MQTT-plugin) to work. Then both the IoT-gateway and telldusmq can communicate through that server.
